import { db } from "hatchable";
export const access = "user";
export const methods = ["POST"];
const clean=v=>String(v??"").trim();
const key=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,"");
const first=(row,aliases)=>{const m=new Map(Object.entries(row).map(([k,v])=>[key(k),v]));for(const a of aliases){const v=m.get(key(a));if(v!==undefined&&v!==null&&clean(v)!=="")return v}return ""};
const mapped=(row,map,aliases)=>{if(map){for(const alias of aliases){const src=map[alias];if(src&&Object.prototype.hasOwnProperty.call(row,src)&&clean(row[src])!=='')return row[src]}}return first(row,aliases)};
const num=(v,d=0)=>{const n=Number(String(v??"").replace(/[,₹$%]/g,"").trim());return Number.isFinite(n)?n:d};
const dateISO=v=>{const s=clean(v);if(!s)return new Date().toISOString().slice(0,10);const d=new Date(s);if(!Number.isNaN(d.getTime()))return d.toISOString().slice(0,10);const m=s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/);return m?`${m[3]}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`:new Date().toISOString().slice(0,10)};
const A={order_id:['order_id','Order ID','Order Id','Order Number','Order No','Amazon Order ID','Sale Order Number','Sub Order No','Sub Order Number'],line:['line_id','Order Item ID','Order Item Id','Line Item ID','Line Item Id','Item ID','Item Id','Sub Order No','Sub Order Number'],sku_code:['sku_code','SKU','Seller SKU','Seller SKU ID','Product SKU','SKU ID','Item SKU','Style ID','Product ID'],order_date:['order_date','Order Date','Order Date/Time','Sale Date','Purchase Date','Created Date','Date'],qty_ordered:['qty_ordered','Qty Ordered','Quantity Ordered','Order Qty','Quantity','Qty','Units','Item Quantity'],qty_delivered:['qty_delivered','Qty Delivered','Quantity Delivered','Delivered Qty','Delivered Quantity','Qty Shipped','Quantity Shipped'],qty_returned:['qty_returned','Qty Returned','Quantity Returned','Returned Qty','Return Quantity','Return Qty'],sale_price:['sale_price','Sale Price/Unit','Selling Price','Selling Price/Unit','Sale Price','Item Price','Product Sale Price','Price','Amount'],status:['status','Order Status','Shipment Status','Status'],delivery_date:['delivery_date','Delivery Date','Fulfillment Date','Ship Date'],return_date:['return_date','Return Date','Returned Date'],location:['customer_location','Customer City/State','Customer Location','Ship To City','Shipping City','City','State'],refund_amount:['refund_amount','Refund Amount','Refund','Refunded Amount']};
const status=s=>{const x=clean(s).toLowerCase();if(!x)return'Delivered';if(x.includes('return'))return'Returned';if(x.includes('cancel'))return'Cancelled';if(x.includes('deliver')||x.includes('complete')||x.includes('shipped'))return'Delivered';if(x.includes('pack'))return'Packed';return'Pending'};
export default async function(req,res){
  const owner=req.user.id,b=req.body||{},platform=clean(b.platform),rows=Array.isArray(b.rows)?b.rows:[],source=clean(b.source_file)||'Marketplace report',map=b.mapping||null;
  if(!['Amazon','Flipkart','Meesho','Shopify','Offline'].includes(platform))return res.status(400).json({error:'Select a supported platform.'});
  if(!rows.length)return res.status(400).json({error:'No rows were found in the report.'});
  const sr=await db.query('SELECT id,sku_code,selling_price FROM skus WHERE created_by=$1 AND platform=$2',[owner,platform]);
  const skuMap=new Map(sr.rows.map(x=>[key(x.sku_code),x]));
  const norm=[];let unmatched=0;
  for(const raw of rows){const orderId=clean(mapped(raw,map,A.order_id)),skuCode=clean(mapped(raw,map,A.sku_code));if(!orderId||!skuCode){unmatched++;continue}const sku=skuMap.get(key(skuCode));if(!sku){unmatched++;continue}const line=clean(mapped(raw,map,A.line))||(orderId+'::'+sku.id),st=status(mapped(raw,map,A.status)),q=num(mapped(raw,map,A.qty_ordered),1),d=mapped(raw,map,A.qty_delivered);norm.push({date:dateISO(mapped(raw,map,A.order_date)),orderId,line,skuId:sku.id,qty:q,delivered:d===''?(st==='Delivered'?q:0):num(d),returned:num(mapped(raw,map,A.qty_returned)),price:num(mapped(raw,map,A.sale_price),Number(sku.selling_price||0)),st,location:clean(mapped(raw,map,A.location))||null,refund:num(mapped(raw,map,A.refund_amount))});}
  const ex=await db.query('SELECT line_key FROM business_orders WHERE created_by=$1 AND platform=$2',[owner,platform]),keys=new Set(ex.rows.map(x=>x.line_key)),seen=new Set();let duplicate=0;const fresh=[];for(const r of norm){if(keys.has(r.line)||seen.has(r.line)){duplicate++;continue}seen.add(r.line);fresh.push(r)}
  const batch=await db.query('INSERT INTO sales_import_batches (created_by,platform,file_name,total_rows,duplicate_rows,unmatched_rows) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id',[owner,platform,source,rows.length,duplicate,unmatched]);const batchId=batch.rows[0].id;let imported=0;
  for(const r of fresh){const ins=await db.query(`INSERT INTO business_orders (created_by,order_date,platform,order_id,line_key,sku_id,qty_ordered,qty_delivered,qty_returned,sale_price,status,customer_location,refund_amount,import_batch_id,source_file,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,now()) ON CONFLICT (created_by,platform,line_key) DO NOTHING RETURNING id`,[owner,r.date,platform,r.orderId,r.line,r.skuId,r.qty,r.delivered,r.returned,r.price,r.st,r.location,r.refund,batchId,source]);if(ins.rows.length)imported++;}
  await db.query(`DELETE FROM sku_transactions WHERE created_by=$1 AND source='AUTO_IMPORT' AND order_id IN (SELECT id FROM business_orders WHERE created_by=$1 AND import_batch_id=$2)`,[owner,batchId]);
  await db.query(`DELETE FROM material_transactions WHERE created_by=$1 AND source='AUTO_IMPORT' AND order_id IN (SELECT id FROM business_orders WHERE created_by=$1 AND import_batch_id=$2)`,[owner,batchId]);
  const os=await db.query(`SELECT o.id,o.order_date,o.delivery_date,o.return_date,o.order_id,o.qty_delivered,o.qty_returned,o.sku_id,s.cost_per_unit FROM business_orders o JOIN skus s ON s.id=o.sku_id WHERE o.created_by=$1 AND o.import_batch_id=$2`,[owner,batchId]);
  for(const o of os.rows){if(Number(o.qty_delivered)>0){await db.query(`INSERT INTO sku_transactions (created_by,txn_date,sku_id,txn_type,qty_out,unit_cost,order_id,reference,source) VALUES ($1,$2,$3,'SALE_OUT',$4,$5,$6,$7,'AUTO_IMPORT')`,[owner,o.delivery_date||o.order_date,o.sku_id,o.qty_delivered,o.cost_per_unit,o.id,o.order_id]);const bom=await db.query(`SELECT sm.material_id,sm.qty_per_unit,sm.waste_pct,m.avg_unit_cost FROM sku_materials sm JOIN materials m ON m.id=sm.material_id WHERE sm.sku_id=$1 AND sm.created_by=$2`,[o.sku_id,owner]);for(const i of bom.rows){const q=Number(o.qty_delivered)*Number(i.qty_per_unit||0)*(1+Number(i.waste_pct||0)/100);if(q>0)await db.query(`INSERT INTO material_transactions (created_by,txn_date,material_id,txn_type,qty_out,unit_cost,order_id,sku_id,reference,source) VALUES ($1,$2,$3,'SALE_OUT',$4,$5,$6,$7,$8,'AUTO_IMPORT')`,[owner,o.delivery_date||o.order_date,i.material_id,q,i.avg_unit_cost,o.id,o.sku_id,o.order_id])}}if(Number(o.qty_returned)>0)await db.query(`INSERT INTO sku_transactions (created_by,txn_date,sku_id,txn_type,qty_in,unit_cost,order_id,reference,source) VALUES ($1,$2,$3,'RETURN_IN',$4,$5,$6,$7,'AUTO_IMPORT')`,[owner,o.return_date||o.order_date,o.sku_id,o.qty_returned,o.cost_per_unit,o.id,o.order_id]);}
  await db.query('UPDATE sales_import_batches SET imported_rows=$1 WHERE id=$2',[imported,batchId]);
  res.json({batch_id:batchId,file_name:source,platform,total_rows:rows.length,imported_rows:imported,duplicate_rows:duplicate,unmatched_rows:unmatched,mapping_used:!!map,message:imported?`Imported ${imported} new rows. ${duplicate} duplicates were skipped.`:'No new rows were imported.'});
}